# Generated by Django 5.0.2 on 2024-12-06 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_personnel_employee_product_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('tel_number', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('mail', models.EmailField(max_length=200)),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
        ),
    ]
