# Generated by Django 5.0.2 on 2024-12-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_rename_customer_information_sales_customer_management_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_edit',
            field=models.BooleanField(default=True),
        ),
    ]
