# Generated by Django 5.0.2 on 2024-12-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_sales_customer_delete_sales_customer_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer_details',
            field=models.BooleanField(default=True),
        ),
    ]
