# Generated by Django 5.0.2 on 2024-12-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_item_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='product_name',
            new_name='item_name',
        ),
    ]
