# Generated by Django 5.0.2 on 2024-12-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_rename_product_id_item_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
