# Generated by Django 5.0.2 on 2024-12-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_order_item_remove_order_customer_delete_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.item')),
            ],
        ),
    ]
